language: r

sudo: required

warnings_are_errors: true

r_build_args: 
r_check_args: --as-cran

r_github_packages: 
  - gluc/libdes

notifications:
  email:
    on_success: change
    on_failure: change
