language: r

sudo: required

- ./travis-tool.sh install_github gluc/libdes

warnings_are_errors: true

r_build_args: 
r_check_args: --as-cran


notifications:
  email:
    on_success: change
    on_failure: change
