language: r

sudo: required

warnings_are_errors: true

r_build_args: 
r_check_args: --as-cran

r_github_packages:
  - jimhester/covr
  - gluc/libdes

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change